[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [
    { access = "read", path = "./forge-artifacts/" },
    { access = "read", path = "./broadcast/" },
]

[rpc_endpoints]
mainnet = "${ALCHEMY_ETH_MAINNET_RPC_URL}"
goerli = "${ALCHEMY_ETH_GOERLI_RPC_URL}"
anvil = "${LOCAL_RPC_URL}"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
